backend:
  name: git-gateway
  repo: josh-unwin/joshunwin
  branch: master

media_folder: "src/project-images"

collections:
- name: "code-projects" # Used in routes, e.g., /admin/collections/blog
  label: "Code Projects" # Used in the UI
  folder: "src/projects-markdown" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Url", name: "url", widget: "string"}
    - {label: "Repo", name: "repo", widget: "string"}
    - {label: "Date", name: "date", widget: "datetime"}
    - {label: "Image", name: "image", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags",
       name: "tags",
       widget: "select",
       multiple: true,
       options: ["React", "Javascript", "Gatsby", "NextJS", "SQL", "Rails", "Ruby"]
      }