backend:
  name: git-gateway
  repo: josh-unwin/joshunwin
  branch: master

site_url: https://www.joshunwin.com

collections:
- name: "projects"
  label: "Projects"
  folder: "src/projects-markdown"
  media_folder: "src/project-images"
  public_folder: "../project-images"
  create: true
  slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
  fields: # The fields for each document, usually in front matter
    - {label: "Project Title", name: "title", widget: "string"}
    - {label: "Project URL", name: "url", widget: "string", required: false}
    - {label: "Repo URL", name: "repo", widget: "string", required: false}
    - {label: "Date", name: "date", widget: "datetime"}
    - {label: "Image", name: "image", widget: "image"}
    - {label: "Technologies",
       name: "technologies",
       widget: "select",
       multiple: true,
       options: ["React", "Javascript", "Gatsby", "NextJS", "SQL", "Rails", "Ruby"]
      }
    - {label: "Contribution",
     name: "contribution",
     widget: "select",
     options: ["1-Lead developer", "2-Key developer", "3-Small contribution to open source"]
    }
    - {label: "Body", name: "body", widget: "markdown"}

- name: "blog"
  label: "Blog"
  folder: "src/blog"
  create: true
  media_folder: ''
  public_folder: ''
  path: "{{slug}}-{{year}}-{{month}}-{{day}}"
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Sub Title", name: "subtitle", widget: "string"}
    - {label: "Date", name: "date", widget: "datetime"}
    - {label: "Image", name: "image", widget: "image"}
    - {label: "Categories",
       name: "categories",
       widget: "select",
       multiple: true,
       options: ["Climate", "Environment", "Tech", "Web Development"]
      }
    - {label: "Body", name: "body", widget: "markdown"}