backend:
  name: git-gateway
  repo: josh-unwin/joshunwin
  branch: master

media_folder: "src/project-images"
public_folder: "../project-images"

collections:
- name: "projects"
  label: "Project"
  folder: "src/projects-markdown"
  create: true
  slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
  fields: # The fields for each document, usually in front matter
    - {label: "Project Title", name: "title", widget: "string"}
    - {label: "Project URL", name: "url", widget: "string", required: false}
    - {label: "Repo URL", name: "repo", widget: "string", required: false}
    - {label: "Date", name: "date", widget: "datetime"}
    - {label: "Image", name: "image", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Technologies",
       name: "technologies",
       widget: "select",
       multiple: true,
       options: ["React", "Javascript", "Gatsby", "NextJS", "SQL", "Rails", "Ruby"]
      }
    - {label: "Contribution",
     name: "contribution",
     widget: "select",
     options: ["Sole developer", "Key developer", "Small contribution to open source"]
    }